version: 2
jobs:
  node:
    working_directory: ~/demo-react-native
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: jest tests
          command: |
            mkdir -p test-results/jest
            yarn run test
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml

      - persist_to_workspace:
          root: ~/demo-react-native
          paths:
            - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

  android:
    working_directory: ~/demo-react-native/android
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - checkout:
          path: ~/demo-react-native

      - attach_workspace:
          at: ~/demo-react-native

      - restore_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}

      - run:
          name: accept Android SDK licenses
          command: |
            sdkmanager --update
            (echo y; echo y; echo y; echo y; echo y; echo y) | $ANDROID_HOME/tools/bin/sdkmanager --licenses
            
      - run: bundle install

      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle

      - run:
          name: fastlane tests
          command: |
            mkdir -p test-results/fastlane
            bundle exec fastlane test
            mv fastlane/report.xml test-results/fastlane

      - store_test_results:
          path: test-results

      # - store_artifacts:
      #     path: test-results

      - run:
          name: fastlane nightly
          command: |
            mkdir -p nightly-results/fastlane
            bundle exec fastlane nightly
            mv app/build/outputs/apk/app-release-unsigned.apk nightly-results/fastlane

      # - store_artifacts:
      #     path: nightly-results

      - run:
          name: upload to Github Releases
          command: | 
            curl -O https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz
            tar xvf go1.12.5.linux-amd64.tar.gz
            sudo chown -R root:root ./go
            sudo mv go /usr/local
            export GOPATH=$HOME/work
            export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
            go get -u github.com/tcnksm/ghr
            VERSION=1.2.3.4
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

workflows:
  version: 2
  node-android:
    jobs:
      - node
      - android:
          requires:
            - node
